@host=http://localhost:5268

POST {{host}}/authentication/register
Content-Type: application/json

{
    "FirstName": "Carlos",
    "LastName": "Medina",
    "Email": "carlos@google.com",
    "Password": "Amiko1234!!"
}