@host=http://localhost:5268
@userId=fdc9fc10-5867-4bef-b68f-c7265e7e3ce3
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiQ2FybG9zIiwiZmFtaWx5X25hbWUiOiJNZWRpbmEiLCJlbWFpbCI6ImNhcmxvc0Bnb29nbGUuY29tIiwiaWQiOiJmZGM5ZmMxMC01ODY3LTRiZWYtYjY4Zi1jNzI2NWU3ZTNjZTMiLCJwZXJtaXNzaW9ucyI6WyJneW1zOmNyZWF0ZSIsImd5bXM6dXBkYXRlIl0sImV4cCI6MTcyNTA1MjQ2MiwiaXNzIjoiR3ltTWFuYWdlbWVudCIsImF1ZCI6Ikd5bU1hbmFnZW1lbnQifQ.zbC8Gc_P4W9kZ_3OdgMPDH_iOccSCQefQ5pE3eYknOw
###
POST {{host}}/users/{{userId}}/profiles/admin
Authorization:Bearer {{token}}

###

### Trainer
POST {{host}}/users/{{userId}}/profiles/trainer

### Participant
POST {{host}}/users/{{userId}}/profiles/participant