@host=http://localhost:5268
@userId=3b2db3a3-a943-4e23-a4ea-e80cc7932aea

POST {{host}}/users/{{userId}}/profiles/admin

### Trainer
POST {{host}}/users/{{userId}}/profiles/trainer

### Participant
POST {{host}}/users/{{userId}}/profiles/participant