@host = http://localhost:5268

# Starter, Pro

POST {{host}}/subscriptions/
Accept: application/json
Content-Type: application/json

{
  "subscriptionType": "Starter",
  "adminId": "2150e333-8fdc-42a3-9474-1a3956d46de8"
}
###