@host = http://localhost:5268

# Starter, Pro

POST {{host}}/subscriptions/
Accept: application/json
Content-Type: application/json

{
  "subscriptionType": "Pro",
  "adminId": "6a19d105-8971-47f7-945e-ac6d28363848"
}
###